version: '3.8'
services:
  #MongoDB
  mongodb_container:
    image: mongo:latest
    ports: 
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  #PostgreSQL
  postgres:
    image: postgres:latest
    ports: 
      - 5432:5432
    volumes:
      - psql_data_container:/data/postgres
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "ignaciodejesus.m.u@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "80:80"
    depends_on:
      - postgres

volumes:
  mongodb_data_container:
  psql_data_container: